#!/bin/bash
# -*-bash-*-

display_usage() {
    echo "Usage:"
    echo "  bash $0 [target] [analysis]"
    echo ""
    echo "Options:"
    echo "  target:   test_case, test_case2"
    echo "  analysis: modref, escape"
}

# if fewer than two arguments supplied, display usage
if [ $# -le 1 ]; then
    display_usage
    exit 1
fi

# check whether user had supplied -h or --help
if [[ ( $# == "--help") ||  $# == "-h" ]]; then
    display_usage
    exit 0
fi

REF="sample_output/$1/"
OUT="examples/$1/chord_output/"

if [ ${PWD##*/} != "constraints" ]; then
    echo "This script must be executed from within the 'constraints' directory."
    exit 1
fi

echo "BUILDING ($1, $2)"
ant -Dchord.work.dir=examples/$1/ $2

if [ $? -eq 0 ]; then
    echo
    echo "CHECKING RESULTS"
    if hash nodejs 2>/dev/null; then
        nodejs ./checker/index.js $1 $2
    else
        node ./checker/index.js $1 $2
    fi
    exit 0
else
    echo "--------------------------------------------------------------------------------"
    echo "Last 25 lines of "$OUT"log.txt are:"
    echo "<<<"
    tail -n 25 $OUT"log.txt"
    echo ">>>"
    exit 1
fi
